version = 0.1
[default.deploy.parameters]
stack_name = "express-lambda-web-adapter-test"
resolve_s3 = true
s3_prefix = "express-lambda-web-adapter-test"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
